// Code generated by the TS compiler without any syntax errors or warnings

class Counter {
  private count = 0;

  increment(): void {
    this.count++;
  }

  getCount(): number {
    return this.count;
  }
}
